
export const LOCAL_LOCATIONS = [
  // Quận/Huyện Hà Nội
  { name: "Quận Ba Đình, Hà Nội", shortName: "Ba Đình" },
  { name: "Quận Hoàn Kiếm, Hà Nội", shortName: "Hoàn Kiếm" },
  { name: "Quận Tây Hồ, Hà Nội", shortName: "Tây Hồ" },
  { name: "Quận Long Biên, Hà Nội", shortName: "Long Biên" },
  { name: "Quận Cầu Giấy, Hà Nội", shortName: "Cầu Giấy" },
  { name: "Quận Đống Đa, Hà Nội", shortName: "Đống Đa" },
  { name: "Quận Hai Bà Trưng, Hà Nội", shortName: "Hai Bà Trưng" },
  { name: "Quận Hoàng Mai, Hà Nội", shortName: "Hoàng Mai" },
  { name: "Quận Thanh Xuân, Hà Nội", shortName: "Thanh Xuân" },
  { name: "Huyện Sóc Sơn, Hà Nội", shortName: "Sóc Sơn" },
  { name: "Huyện Đông Anh, Hà Nội", shortName: "Đông Anh" },
  { name: "Huyện Gia Lâm, Hà Nội", shortName: "Gia Lâm" },
  { name: "Quận Nam Từ Liêm, Hà Nội", shortName: "Nam Từ Liêm" },
  { name: "Quận Bắc Từ Liêm, Hà Nội", shortName: "Bắc Từ Liêm" },
  { name: "Huyện Thanh Trì, Hà Nội", shortName: "Thanh Trì" },
  { name: "Huyện Mê Linh, Hà Nội", shortName: "Mê Linh" },
  { name: "Quận Hà Đông, Hà Nội", shortName: "Hà Đông" },
  { name: "Thị xã Sơn Tây, Hà Nội", shortName: "Sơn Tây" },
  { name: "Huyện Ba Vì, Hà Nội", shortName: "Ba Vì" },
  { name: "Huyện Phúc Thọ, Hà Nội", shortName: "Phúc Thọ" },
  { name: "Huyện Đan Phượng, Hà Nội", shortName: "Đan Phượng" },
  { name: "Huyện Hoài Đức, Hà Nội", shortName: "Hoài Đức" },
  { name: "Huyện Quốc Oai, Hà Nội", shortName: "Quốc Oai" },
  { name: "Huyện Thạch Thất, Hà Nội", shortName: "Thạch Thất" },
  { name: "Huyện Chương Mỹ, Hà Nội", shortName: "Chương Mỹ" },
  { name: "Huyện Thanh Oai, Hà Nội", shortName: "Thanh Oai" },
  { name: "Huyện Thường Tín, Hà Nội", shortName: "Thường Tín" },
  { name: "Huyện Phú Xuyên, Hà Nội", shortName: "Phú Xuyên" },
  { name: "Huyện Ứng Hòa, Hà Nội", shortName: "Ứng Hòa" },
  { name: "Huyện Mỹ Đức, Hà Nội", shortName: "Mỹ Đức" },

  // Xã/Thị trấn Huyện Giao Thủy, Nam Định
  { name: "Thị trấn Ngô Đồng, Giao Thủy, Nam Định", shortName: "Thị trấn Ngô Đồng" },
  { name: "Thị trấn Quất Lâm, Giao Thủy, Nam Định", shortName: "Thị trấn Quất Lâm" },
  { name: "Xã Giao An, Giao Thủy, Nam Định", shortName: "Xã Giao An" },
  { name: "Xã Giao Châu, Giao Thủy, Nam Định", shortName: "Xã Giao Châu" },
  { name: "Xã Giao Hà, Giao Thủy, Nam Định", shortName: "Xã Giao Hà" },
  { name: "Xã Giao Hải, Giao Thủy, Nam Định", shortName: "Xã Giao Hải" },
  { name: "Xã Giao Hương, Giao Thủy, Nam Định", shortName: "Xã Giao Hương" },
  { name: "Xã Giao Lạc, Giao Thủy, Nam Định", shortName: "Xã Giao Lạc" },
  { name: "Xã Giao Long, Giao Thủy, Nam Định", shortName: "Xã Giao Long" },
  { name: "Xã Giao Nhân, Giao Thủy, Nam Định", shortName: "Xã Giao Nhân" },
  { name: "Xã Giao Phong, Giao Thủy, Nam Định", shortName: "Xã Giao Phong" },
  { name: "Xã Giao Tân, Giao Thủy, Nam Định", shortName: "Xã Giao Tân" },
  { name: "Xã Giao Thanh, Giao Thủy, Nam Định", shortName: "Xã Giao Thanh" },
  { name: "Xã Giao Thiện, Giao Thủy, Nam Định", shortName: "Xã Giao Thiện" },
  { name: "Xã Giao Thịnh, Giao Thủy, Nam Định", shortName: "Xã Giao Thịnh" },
  { name: "Xã Giao Tiến, Giao Thủy, Nam Định", shortName: "Xã Giao Tiến" },
  { name: "Xã Giao Xuân, Giao Thủy, Nam Định", shortName: "Xã Giao Xuân" },
  { name: "Xã Giao Yến, Giao Thủy, Nam Định", shortName: "Xã Giao Yến" },
  { name: "Xã Hồng Thuận, Giao Thủy, Nam Định", shortName: "Xã Hồng Thuận" },
  { name: "Xã Bạch Long, Giao Thủy, Nam Định", shortName: "Xã Bạch Long" },
  { name: "Xã Bình Hòa, Giao Thủy, Nam Định", shortName: "Xã Bình Hòa" },
  { name: "Xã Vĩnh Quang, Giao Thủy, Nam Định", shortName: "Xã Vĩnh Quang" }
];
